version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: budget-postgres
    environment:
      POSTGRES_DB: budget_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    command: postgres -c password_encryption=md5

volumes:
  postgres_data:
    driver: local